### ISSUE TITLE
请问如何获得tsen.mat文件

### ISSUE THREAD

**Issue by zhangzhang1524** [ZYK100/LLCM#1]
FileNotFoundError: [Errno 2] No such file or directory: 'tsne.mat'

**Comment by ZYK100** [comment]
Hi, you can obtain the 'tsne.mat' by running: 
```
python extract.py --dataset llcm --method agw --gpu 0
```

**Comment by zhangzhang1524** [comment]
(pytorch) root@:/LLCM-main/AGW# python extract.py --dataset llcm --method agw --gpu 0
==> Building model..
==> Loading data..
(pytorch) root@iao:/LLCM-main/AGW# ls
data_loader.py   eval_metrics.py  imgs                     log      model.py             __pycache__        ranking.py  resnet.py   test.py   tsne.py
data_manager.py  extract.py       intra_inter-distance.py  loss.py  pre_process_sysu.py  random_erasing.py  README.md   save_model  train.py  utils.py

抱歉，运行之后并未获得.mat文件

**Comment by ZYK100** [comment]
It seems that you have modified the code, resulting in no feature extraction.

**Comment by zhangzhang1524** [comment]
谢谢，经过检查是中间出了问题，谢谢您的帮助，祝您生活愉快，万事顺利。
