### ISSUE TITLE
Question about testing

### ISSUE THREAD

**Issue by EDDChang** [ZYK100/LLCM#10]
Hi, thanks for your great work.
I would like to know in VIReID, which of the following is correct setting?
1. Train a SINGLE model to deal with 2 testing model: VIS->IR and IR->VIS. or
2. For each mode, we could train a model respectively. That is,  a model can only handle IR->VIS model and another model can only handle VIS->IR mode.
Thanks for your response.

**Comment by ZYK100** [comment]
Hi, 1 is  correct setting. You only need to train one model.

**Comment by EDDChang** [comment]
But in your DEEN train.py, test mode is set to [0, 1] or [1, 0]. Does that mean you train your model twice? One for VIS->IR and another for IR->VIS and can not get a ckpt optimal in one training process for 2 modes?

**Comment by ZYK100** [comment]
You only need to train one model. During testing, you can modify the testing mode for VIS to NIR or NIR to VIS.

**Comment by ZYK100** [comment]
In DEEN train.py, the test mode is set to [0, 1] or [1, 0], which is used to validation.
