### ISSUE TITLE
关于实验结果

### ISSUE THREAD

**Issue by MengWH** [ZYK100/LLCM#13]
您好，请问为什么您的代码在SYSU-MM01数据集上的效果在我本地结果为71.08% 与您论文中差了3个点
不知道是不是因为还需要参数的设置之类的。
还有您的代码中img_w和img_h分别设置为了144和384，能解释一下为什么这么设置吗（因为我本地是设置为192和384，不知道是不是因为这个原因导致结果相差比较多）

![972953399e4acf7c7b1250e6bc4822f](https://github.com/ZYK100/LLCM/assets/48003067/4e816b01-4fbd-4a32-a981-7e3eeb4fd7b3)

**Comment by ZYK100** [comment]
您好，和图像resize的大小关系不大，可能是您哪里的参数设置错了。我们开源的性能比论文中还要高出一些来，您可以再调试一下参数试试
