### ISSUE TITLE
A minor mistake of codes

### ISSUE THREAD

**Issue by dyhBUPT** [ZYK100/LLCM#14]
Hi, thanks for your great contribution~
Maybe there is a minor mistake of the training code.

Maybe we should change:
https://github.com/ZYK100/LLCM/blob/cd72993613cc1731ee0b6d6a4240ff8598ad93ad/DEEN/train.py#L274-L275
to 
```python
labs = torch.cat((label1, label2, label1, label2), 0)
labels = torch.cat((label1, label2, label1, label2, label1, label2), 0)
```

This doesn't influence the training process, because `label1 == label2`.
However, the original codes are logically wrong.

**Comment by ZYK100** [comment]
Thank you for valuable suggestions. The codes are revised accordingly.
