### ISSUE TITLE
Exp on RegDB

### ISSUE THREAD

**Issue by dyhBUPT** [ZYK100/LLCM#19]
Hi, thanks for your work and codes.

I'm conducting experiments on RegDB, and I have some questions:
- On RegDB, I need to train the model 10 times with trails 1~10 ?
- To reproduce the reported results of your paper, do I need to tune any hyper-parameters for RegDB ?

Thank you~

**Comment by dyhBUPT** [comment]
Thanks for your reply~

I have trouble in reproducing the results on RegDB now.
It would be great help if you can provide the training log.

Best wishes.

**Comment by dyhBUPT** [comment]
Maybe I've figure out the problem.
For RegDB, if I want to test with "IR to RGB", only modifying the `test_mode` is not enough.
I should also exchange the `modal` in these two lines:
https://github.com/ZYK100/LLCM/blob/c73b6c2d70f46c336df01a7e2d326849e055820d/DEEN/train.py#L159-L160

**Comment by Glisten-5481** [comment]
Hello, I'm sorry to bother you. Did the approach you mentioned above solve the problem?  if I still need to retrain the model？@dyhBUPT

**Comment by dyhBUPT** [comment]
> Hello, I'm sorry to bother you. Did the approach you mentioned above solve the problem? @dyhBUPT

Yes, for now my evaluation results on RegDB are right

**Comment by Glisten-5481** [comment]
Thank you very much! I also want to ask if I need to retrain?

dyhBUPT ***@***.***> 于2024年1月8日周一 11:27写道：

**Comment by Glisten-5481** [comment]
Thank you very much! This helps me a lot. I also want to ask if I need to retrain? @dyhBUPT

**Comment by dyhBUPT** [comment]
To my understanding, it's not necessary, but it's best to retrain.

> Thank you very much! This helps me a lot. I also want to ask if I need to retrain? @dyhBUPT

**Comment by eatgreenjiao** [comment]
> 你好，感谢您的工作和代码。
> 
> 我正在对RegDB进行实验，有一些问题：
> 
> * 在 RegDB 上，我需要使用 1~10 次试验对模型进行 10 次训练？
> * 为了重现您论文中报告的结果，我需要调整 RegDB 的任何超参数吗？
> 
> 谢谢〜

你好，我在sysu数据集上的结果差了好几个点，也是按照作者的源代码进行训练和测试的，请问有什么地方需要注意吗

**Comment by ZYK100** [comment]
> > 你好，感谢您的工作和代码。
> > 我正在对RegDB进行实验，有一些问题：
> > 
> > * 在 RegDB 上，我需要使用 1~10 次试验对模型进行 10 次训练？
> > * 为了重现您论文中报告的结果，我需要调整 RegDB 的任何超参数吗？
> > 
> > 谢谢〜
> 
> 你好，我在sysu数据集上的结果差了好几个点，也是按照作者的源代码进行训练和测试的，请问有什么地方需要注意吗

您好， RegDB数据集上需要 进行10次训练和测试，无需修改任务参数，SYSU数据集同样也是，这个代码目前为止还没有人反馈说结果低了很多的，你可以先不要修改参数训练试试。
