### ISSUE TITLE
你代码里的损失与论文中的损失不一样？

### ISSUE THREAD

**Issue by Jack-zz-ze** [ZYK100/LLCM#2]
![image](https://user-images.githubusercontent.com/66547834/233366906-6a4a597a-038c-4a7f-86f1-95af2a404f8b.png)
只有前面的交叉熵和三元组损失。
同时在训练的时候，你的CPM损失，如何生成原始嵌入和生成的嵌入，这个并没有在代码中体现。

**Comment by ZYK100** [comment]
目前开源的是我们的数据集LLCM和基线代码AGW以供大家测试，我们论文的代码DEEN稍后会开源
