### ISSUE TITLE
extract.py

### ISSUE THREAD

**Issue by 1126138640** [ZYK100/LLCM#21]
非常感谢您的工作，请问在使用已经训练好的权重执行extract.py文件时，出现了以下错误，但是在执行test.py时并没出现，执行的命令是python extract.py --dataset sysu --method agw --gpu 0；权重文件是sysu_agw_p4_n8_lr_0.1_seed_0_best.t
![01](https://github.com/ZYK100/LLCM/assets/27566480/f3400bad-98c2-4d90-bc69-f19a0ae12a46)

**Comment by ZYK100** [comment]
您好，感谢您对我们工作的关注~如果是我们的模型的话，你加载的模型是sysu_deen_p4_n6_lr_0.1_seed_0_best.t

**Comment by 1126138640** [comment]
好的，感谢您的回复，我测试使用的方法是AGW

**Comment by GG0614** [comment]
> 好的，感谢您的回复，我测试使用的方法是AGW

你好，我也遇到了这个问题，请问你解决了吗
