### ISSUE TITLE
regdb test result

### ISSUE THREAD

**Issue by JUN-KAI-FAN** [ZYK100/LLCM#25]
Based on the author's provided `train_regdb.bash` script, I trained the model and used the following command for testing:

```bash
python test.py --tvsearch True --gpu 0 --dataset regdb
```

However, the results significantly differ from those reported in the author's paper. Can you explain why this discrepancy might occur?

**Comment by JUN-KAI-FAN** [comment]
![螢幕擷取畫面 2024-06-16 175316](https://github.com/ZYK100/LLCM/assets/88937319/264f4e20-ae73-45a0-b8c8-b38e9758db7b)

**Comment by ZYK100** [comment]
您好，您是不是测试反了，regdb有两种模式，测试的时候需要修改一下

**Comment by JUN-KAI-FAN** [comment]
> 您好，您是不是测试反了，regdb有两种模式，测试的时候需要修改一下

謝謝作者回復，確實照修改完後正常，另外想問作者sysu的數據集作者是否有做甚麼改動，因為測試時發現all search模式測下來跟作者差4個百分點
![螢幕擷取畫面 2024-06-17 163027](https://github.com/ZYK100/LLCM/assets/88937319/3bfbc0ba-22fd-4025-a0ef-2967d0d0f9ed)

**Comment by ZYK100** [comment]
sysu数据集没有改动，你需要按照我们的设置进行训练和测试，这个代码经过很多人的测试和实验了，表明是没问题的

**Comment by JUN-KAI-FAN** [comment]
> sysu数据集没有改动，你需要按照我们的设置进行训练和测试，这个代码经过很多人的测试和实验了，表明是没问题的

作者您好，剛發現我的留言可能會讓您誤會我質疑您訓練數據有偷吃步，這點跟作者誠懇的道歉，本人絕對相信作者的實驗數據是完整無誤的，也相信是沒問題的，目前發現我在pre_process_sysu.py的程式與作者有落差，重新跑過作者提供的pre_process_sysu.py並重新跑訓練，其他訓練參數皆使用作者預設的設置進行訓練，等訓練完成後會更新現況，謝謝作者的回覆

**Comment by JUN-KAI-FAN** [comment]
> sysu数据集没有改动，你需要按照我们的设置进行训练和测试，这个代码经过很多人的测试和实验了，表明是没问题的

作者您好，修改完後結果已經跟您實驗數據差不多了。
![擷取](https://github.com/ZYK100/LLCM/assets/88937319/113c60b2-1688-4736-bba7-67154759a29c)
