### ISSUE TITLE
llcm数据集

### ISSUE THREAD

**Issue by speaker111** [ZYK100/LLCM#28]
您好，请问我跑了您的deen网络中的llcm数据集的test另外一个模式结果和训练的相差有点大，训练的准确率是正常的，但是test有点不一样。

**Comment by eatgreenjiao** [comment]
> 您好，请问我跑了您的deen网络中的llcm数据集的test另外一个模式结果和训练的相差有点大，训练的准确率是正常的，但是test有点不一样。

你好，能提供以下我RegDb的数据集吗，我申请了好长时间没有得到回复

**Comment by ZYK100** [comment]
> 您好，请问我跑了您的deen网络中的llcm数据集的test另外一个模式结果和训练的相差有点大，训练的准确率是正常的，但是test有点不一样。

您好，这个应该是您测试错了，建议您检查一下代码，并且按照我们的要求进行测试

**Comment by ZYK100** [comment]
> > 您好，请问我跑了您的deen网络中的llcm数据集的test另外一个模式结果和训练的相差有点大，训练的准确率是正常的，但是test有点不一样。
> 
> 你好，能提供以下我RegDb的数据集吗，我申请了好长时间没有得到回复

您好，RegDB数据集我当时是向武大的叶芒老师申请的，您可以试试，他的邮箱是：[mangye16@gmail.com](mailto:mangye16@gmail.com)

**Comment by eatgreenjiao** [comment]
> > > 您好，请问我跑了您的deen网络中的llcm数据集的test另外一个模式结果和训练的相差有点大，训练的准确率是正常的，但是test有点不一样。
> > 
> > 
> > 你好，能提供以下我RegDb的数据集吗，我申请了好长时间没有得到回复
> 
> 您好，RegDB数据集我当时是向武大的叶芒老师申请的，您可以试试，他的邮箱是：[mangye16@gmail.com](mailto:mangye16@gmail.com)

作者您好，我申请了您的LLCM数据集使用，希望您查看一下

**Comment by ZYK100** [comment]
> > > > 您好，请问我跑了您的deen网络中的llcm数据集的test另外一个模式结果和训练的相差有点大，训练的准确率是正常的，但是test有点不一样。
> > > 
> > > 
> > > 你好，能提供以下我RegDb的数据集吗，我申请了好长时间没有得到回复
> > 
> > 
> > 您好，RegDB数据集我当时是向武大的叶芒老师申请的，您可以试试，他的邮箱是：[mangye16@gmail.com](mailto:mangye16@gmail.com)
> 
> 作者您好，我申请了您的LLCM数据集使用，希望您查看一下

您好，我邮箱里没收到您的申请，您可以发送申请到我学校的邮箱，或者QQ邮箱：[2197253439@qq.com](mailto:2197253439@qq.com)

**Comment by liujuny5920** [comment]
作者你好，你新贴出的LLCM数据集上的准确率较原论文中的62.5提高到了69.21，包括其他的方法也有相应的上涨，请问是什么原因呢？

**Comment by ZYK100** [comment]
> 作者你好，你新贴出的LLCM数据集上的准确率较原论文中的62.5提高到了69.21，包括其他的方法也有相应的上涨，请问是什么原因呢？

您好，我们对数据集做了一些调整，所以性能与原文相比有些上涨

**Comment by wangyue09** [comment]
您好，我在可视化过程中遇到问题ValueError: Found array with dim 4. TSNE expected <= 2.应该如何解决呢

**Comment by ZYK100** [comment]
> 您好，我在可视化过程中遇到问题ValueError: Found array with dim 4. TSNE expected <= 2.应该如何解决呢

您好，您可以将您修改后的代码发上来吗？我们原始的代码是没有这个问题的，不清楚您做了哪些修改

**Comment by wangyue09** [comment]
> > 您好，我在可视化过程中遇到问题ValueError： Found array with dim 4.TSNE expected <= 2.应该如何解决呢
> 
> 您好，您可以将您修改后的代码发上来吗？我们原始的代码是没有这个问题的，不清楚您做了哪些修改

您好，除了路径我没有对代码进行修改

**Comment by wangyue09** [comment]
from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import offsetbox
import scipy.io
import os
from sklearn import manifold, datasets
import argparse
import sys
import time
import torch
import torch.nn as nn
import torch.optim as optim
import torch.backends.cudnn as cudnn
import torch.nn.functional as F
from torch.autograd import Variable
import torch.utils.data as data
import torchvision
import torchvision.transforms as transforms
from data_loader import SYSUData, RegDBData, LLCMData, TestData
from data_manager import *
from eval_metrics import eval_sysu, eval_regdb, eval_llcm
from model import embed_net
from utils import *
from loss import OriTripletLoss
from random_erasing import RandomErasing
import numpy as np
from PIL import Image
import torch.utils.data as data

parser = argparse.ArgumentParser(description='PyTorch Cross-Modality Training')
parser.add_argument('--dataset', default='sysu', help='dataset name: regdb or sysu]')
parser.add_argument('--lr', default=0.03, type=float, help='learning rate, 0.00035 for adam')
parser.add_argument('--optim', default='sgd', type=str, help='optimizer')
parser.add_argument('--arch', default='resnet50', type=str, help='network baseline:resnet18 or resnet50')
parser.add_argument('--resume', '-r', default='sysu_agw_p4_n8_lr_0.1_seed_0_best.t', type=str, help='resume from checkpoint')
parser.add_argument('--test-only', action='store_true', help='test only')
parser.add_argument('--model_path', default='save_model/', type=str, help='model save path')
parser.add_argument('--save_epoch', default=20, type=int, metavar='s', help='save model every 10 epochs')
parser.add_argument('--log_path', default='log/', type=str, help='log save path')
parser.add_argument('--vis_log_path', default='log/vis_log/', type=str, help='log save path')
parser.add_argument('--workers', default=8, type=int, metavar='N', help='number of data loading workers (default: 4)')
parser.add_argument('--img_w', default=144, type=int, metavar='imgw', help='img width')
parser.add_argument('--img_h', default=288, type=int, metavar='imgh', help='img height')
parser.add_argument('--batch-size', default=20, type=int, metavar='B', help='training batch size')
parser.add_argument('--test-batch', default=64, type=int, metavar='tb', help='testing batch size')
parser.add_argument('--method', default='base', type=str, metavar='m', help='method type: base or agw')
parser.add_argument('--margin', default=0.3, type=float, metavar='margin', help='triplet loss margin')
parser.add_argument('--margin_cc', default=0.1, type=float, metavar='margin', help='triplet loss margin')
parser.add_argument('--num_pos', default=30, type=int, help='num of pos per identity in each modality')
parser.add_argument('--trial', default=1, type=int, metavar='t', help='trial (only for RegDB dataset)')
parser.add_argument('--seed', default=0, type=int, metavar='t', help='random seed')
parser.add_argument('--dist-type', default='l2', type=str, help='type of distance')
parser.add_argument('--gpu', default='0', type=str, help='gpu device ids for CUDA_VISIBLE_DEVICES')
parser.add_argument('--mode', default='all', type=str, help='all or indoor')

args = parser.parse_args()
os.environ['CUDA_VISIBLE_DEVICES'] = args.gpu

set_seed(args.seed)

dataset = args.dataset
if dataset == 'sysu':
&nbsp; &nbsp; data_path = '/root/autodl-tmp/LLCM-main/SYSU-MM01/'
&nbsp; &nbsp; n_class = 395
&nbsp; &nbsp; test_mode = [1, 2]
elif dataset =='regdb':
&nbsp; &nbsp; data_path = './Datasets/RegDB/'
&nbsp; &nbsp; n_class = 206
&nbsp; &nbsp; test_mode = [2, 1]
elif dataset =='llcm':
&nbsp; &nbsp; data_path = './Dataset/LLCM/'
&nbsp; &nbsp; n_class = 713
&nbsp; &nbsp; test_mode = [1, 2] #[2, 1]: VIS to IR; [1, 2]: IR to VIS

checkpoint_path = args.model_path


print("==========\nArgs:{}\n==========".format(args))
device = 'cuda' if torch.cuda.is_available() else 'cpu'
best_acc = 0 &nbsp;# best test accuracy
best_map = 0 &nbsp;# best test map
start_epoch = 0

print('==&gt; Loading data..')
# Data loading code
normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
transform_train_list = [
&nbsp; &nbsp; transforms.ToPILImage(),
&nbsp; &nbsp; transforms.RandomCrop((args.img_h, args.img_w)),
&nbsp; &nbsp; transforms.RandomHorizontalFlip(),
&nbsp; &nbsp; transforms.ToTensor(),
&nbsp; &nbsp; normalize,
]
transform_train = transforms.Compose(transform_train_list)
print(transform_train_list)

transform_test = transforms.Compose([
&nbsp; &nbsp; transforms.ToPILImage(),
&nbsp; &nbsp; transforms.Resize((args.img_h, args.img_w)),
&nbsp; &nbsp; transforms.ToTensor(),
&nbsp; &nbsp; normalize,
&nbsp; &nbsp; RandomErasing(probability = 1, mean=[0.0, 0.0, 0.0]),
])

if not os.path.isdir('./save_tsne'):
&nbsp; &nbsp; os.makedirs('./save_tsne')

result = scipy.io.loadmat('tsne.mat')
query_feature = torch.FloatTensor(result['query_f'])
query_cam = result['query_cam'][0]
query_label = result['query_label'][0]


gallery_feature = torch.FloatTensor(result['gallery_f'])
gallery_cam = result['gallery_cam'][0]
gallery_label = result['gallery_label'][0]

query_feature = query_feature.cuda()
gallery_feature = gallery_feature.cuda()


class LLCMData(data.Dataset):
&nbsp; &nbsp; def __init__(self, data_dir, trial, transform=None, colorIndex = None, thermalIndex = None):
&nbsp; &nbsp; &nbsp; &nbsp; # Load training images (path) and labels
&nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; query_feature = torch.FloatTensor(result['query_f'])
&nbsp; &nbsp; &nbsp; &nbsp; query_cam = result['query_cam'][0]
&nbsp; &nbsp; &nbsp; &nbsp; query_label = result['query_label'][0]
&nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; gallery_feature = torch.FloatTensor(result['gallery_f'])
&nbsp; &nbsp; &nbsp; &nbsp; gallery_cam = result['gallery_cam'][0]
&nbsp; &nbsp; &nbsp; &nbsp; gallery_label = result['gallery_label'][0]
&nbsp; &nbsp; &nbsp; &nbsp; 

&nbsp; &nbsp; &nbsp; &nbsp; # BGR to RGB
&nbsp; &nbsp; &nbsp; &nbsp; self.train_color_image = query_feature &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; self.train_color_label = query_label
&nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; # BGR to RGB
&nbsp; &nbsp; &nbsp; &nbsp; self.train_thermal_image = gallery_feature
&nbsp; &nbsp; &nbsp; &nbsp; self.train_thermal_label = gallery_label
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; self.transform = transform
&nbsp; &nbsp; &nbsp; &nbsp; self.cIndex = colorIndex
&nbsp; &nbsp; &nbsp; &nbsp; self.tIndex = thermalIndex

&nbsp; &nbsp; def __getitem__(self, index):

&nbsp; &nbsp; &nbsp; &nbsp; img1, &nbsp;target1 = self.train_color_image[self.cIndex[index]], &nbsp;self.train_color_label[self.cIndex[index]]
&nbsp; &nbsp; &nbsp; &nbsp; img2, &nbsp;target2 = self.train_thermal_image[self.tIndex[index]], self.train_thermal_label[self.tIndex[index]]
&nbsp; &nbsp; &nbsp; &nbsp; 

&nbsp; &nbsp; &nbsp; &nbsp; return img1, img2, target1, target2

&nbsp; &nbsp; def __len__(self):
&nbsp; &nbsp; &nbsp; &nbsp; return len(self.train_color_label)



def process_llcm(img_dir, mode = 1):
&nbsp; &nbsp; if mode== 1:
&nbsp; &nbsp; &nbsp; &nbsp; input_data_path = os.path.join(data_path, 'idx/test_vis.txt')
&nbsp; &nbsp; elif mode ==2:
&nbsp; &nbsp; &nbsp; &nbsp; input_data_path = os.path.join(data_path, 'idx/test_nir.txt')
&nbsp; &nbsp; 
&nbsp; &nbsp; with open(input_data_path) as f:
&nbsp; &nbsp; &nbsp; &nbsp; data_file_list = open(input_data_path, 'rt').read().splitlines()
&nbsp; &nbsp; &nbsp; &nbsp; file_image = [img_dir + '/' + s.split(' ')[0] for s in data_file_list]
&nbsp; &nbsp; &nbsp; &nbsp; file_label = [int(s.split(' ')[1]) for s in data_file_list]
&nbsp; &nbsp; &nbsp; &nbsp; file_cam = [int(s.split('c0')[1][0]) for s in data_file_list]
&nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; return file_image, np.array(file_label), np.array(file_cam)
&nbsp; &nbsp; 


end = time.time()
if dataset == 'sysu':
&nbsp; &nbsp; # training set
&nbsp; &nbsp; trainset = SYSUData(data_path, transform=transform_train)
&nbsp; &nbsp; # generate the idx of each person identity
&nbsp; &nbsp; color_pos, thermal_pos = GenIdx(trainset.train_color_label, trainset.train_thermal_label)

&nbsp; &nbsp; # testing set
&nbsp; &nbsp; query_img, query_label, query_cam = process_query_sysu(data_path, mode=args.mode)
&nbsp; &nbsp; gall_img, gall_label, gall_cam = process_gallery_sysu(data_path, mode=args.mode, trial=0)

elif dataset == 'regdb':
&nbsp; &nbsp; # training set
&nbsp; &nbsp; trainset = RegDBData(data_path, args.trial, transform=transform_train)
&nbsp; &nbsp; # generate the idx of each person identity
&nbsp; &nbsp; color_pos, thermal_pos = GenIdx(trainset.train_color_label, trainset.train_thermal_label)

&nbsp; &nbsp; # testing set
&nbsp; &nbsp; query_img, query_label = process_test_regdb(data_path, trial=args.trial, modal='visible')
&nbsp; &nbsp; gall_img, gall_label = process_test_regdb(data_path, trial=args.trial, modal='thermal')

elif dataset == 'llcm':
&nbsp; &nbsp; # training set
&nbsp; &nbsp; trainset = LLCMData(data_path, args.trial, transform=transform_train)
&nbsp; &nbsp; # generate the idx of each person identity
&nbsp; &nbsp; color_pos, thermal_pos = GenIdx(trainset.train_color_label, trainset.train_thermal_label)

&nbsp; &nbsp; # testing set
&nbsp; &nbsp; query_img, query_label, query_cam = process_llcm(data_path, mode=test_mode[1])
&nbsp; &nbsp; gall_img, gall_label, gall_cam = process_llcm(data_path, mode=test_mode[0])

tsne_class = len(np.unique(trainset.train_color_label))

print('Dataset {} statistics:'.format(dataset))
print(' &nbsp;------------------------------')
print(' &nbsp;subset &nbsp; | # ids | # images')
print(' &nbsp;------------------------------')
print(' &nbsp;visible &nbsp;| {:5d} | {:8d}'.format(tsne_class, len(trainset.train_color_label)))
print(' &nbsp;thermal &nbsp;| {:5d} | {:8d}'.format(tsne_class, len(trainset.train_thermal_label)))
print(' &nbsp;------------------------------')
print('Data Loading Time:\t {:.3f}'.format(time.time() - end))

print('==&gt; Building model..')
net = embed_net(n_class, no_local= 'on', gm_pool = 'on', arch=args.arch)
net = net.to(device)
cudnn.benchmark = True

if len(args.resume) &gt; 0:
&nbsp; &nbsp; model_path = checkpoint_path + args.resume
&nbsp; &nbsp; if os.path.isfile(model_path):
&nbsp; &nbsp; &nbsp; &nbsp; print('==&gt; loading checkpoint {}'.format(args.resume))
&nbsp; &nbsp; &nbsp; &nbsp; checkpoint = torch.load(model_path)
&nbsp; &nbsp; &nbsp; &nbsp; start_epoch = checkpoint['epoch']
&nbsp; &nbsp; &nbsp; &nbsp; net.load_state_dict(checkpoint['net'])
&nbsp; &nbsp; &nbsp; &nbsp; print('==&gt; loaded checkpoint {} (epoch {})'
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .format(args.resume, checkpoint['epoch']))
&nbsp; &nbsp; else:
&nbsp; &nbsp; &nbsp; &nbsp; print('==&gt; no checkpoint found at {}'.format(args.resume))

# define loss function
criterion_id = nn.CrossEntropyLoss()
loader_batch = args.batch_size * args.num_pos
criterion_tri = OriTripletLoss(batch_size=loader_batch, margin=args.margin)

criterion_id.to(device)
criterion_tri.to(device)


def plot_embedding(X, y, z, title=None):
&nbsp; &nbsp; x_min, x_max = np.min(X, 0), np.max(X, 0)
&nbsp; &nbsp; X = (X - x_min) / (x_max - x_min)
&nbsp; &nbsp; plt.figure(figsize=(15, 12), dpi=100)
&nbsp; &nbsp; cx, cy = [], []

&nbsp; &nbsp; r = []
&nbsp; &nbsp; #print(X.shape[0])
&nbsp; &nbsp; for i in range(X.shape[0]):
&nbsp; &nbsp; &nbsp; &nbsp; cx.append(X[i, 0])
&nbsp; &nbsp; &nbsp; &nbsp; cy.append(X[i, 1])
&nbsp; &nbsp; &nbsp; &nbsp; if z[i] == 1:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; #print(i, y[i])
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; plt.scatter(X[i, 0], X[i, 1], s=120, color=color[y[i]], edgecolor='black', marker='o')
&nbsp; &nbsp; &nbsp; &nbsp; else:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; plt.scatter(X[i, 0], X[i, 1], s=120, color=color[y[i]], edgecolor='black', marker='^')

color= [(0.1, 0.1, 0.1, 1.0),#r, g, b
&nbsp; &nbsp; &nbsp; &nbsp; (0.5, 0.5, 0.5, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (1.0, 0.6, 0.1, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (1.0, 0.0, 0.0, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (1.0, 0.1, 0.7, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.9, 0.2, 0.4, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.8, 0.2, 1.0, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.8, 0.3, 0.2, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.7, 0.5, 0.3, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.7, 0.9, 0.4, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.7, 0.3, 0.8, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.0, 1.0, 0.0, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.4, 1.0, 0.6, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.3, 0.8, 0.5, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.1, 0.8, 1.0, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.5, 0.7, 0.9, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.4, 0.8, 0.3, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.5, 0.7, 0.4, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.2, 0.6, 0.8, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.1, 0.1, 1.0, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.3, 0.3, 0.9, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; (0.6, 0.1, 0.4, 1.0),
&nbsp; &nbsp; &nbsp; &nbsp; ]#R G B

&nbsp; &nbsp; &nbsp; &nbsp; 
def train(epoch):
&nbsp; &nbsp; #current_lr = adjust_learning_rate(optimizer, epoch)
&nbsp; &nbsp; train_loss = AverageMeter()
&nbsp; &nbsp; id_loss = AverageMeter()
&nbsp; &nbsp; tri_loss = AverageMeter()
&nbsp; &nbsp; cc_loss = AverageMeter()
&nbsp; &nbsp; data_time = AverageMeter()
&nbsp; &nbsp; batch_time = AverageMeter()
&nbsp; &nbsp; correct = 0
&nbsp; &nbsp; total = 0
&nbsp; &nbsp; # switch to train mode
&nbsp; &nbsp; net.eval()
&nbsp; &nbsp; end = time.time()
&nbsp; &nbsp; with torch.no_grad():
&nbsp; &nbsp; &nbsp; for batch_idx, (input1, input2, label1, label2) in enumerate(trainloader):
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; labels = torch.cat((label1, label2), 0)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; z1 = torch.ones(label1.shape)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; z2 = torch.zeros(label2.shape)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; z = torch.cat((z1, z2), 0)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; print(batch_idx)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; input1 = Variable(input1.cuda())
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; input2 = Variable(input2.cuda())
&nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a = labels.unique()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; for i in range(len(a)):
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; for j in range(len(labels)):
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if labels[j] == a[i]:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; labels[j] = i
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; #print(labels)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; data_time.update(time.time() - end)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; out = torch.cat((input1, input2), 0)
&nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; tsne = manifold.TSNE(n_components=2, init='pca', random_state=0)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; X_tsne = tsne.fit_transform(out.detach().cpu().numpy())
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; plot_embedding(X_tsne, labels, z)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; plt.savefig(osp.join('save_tsne', 'tsne_{}.jpg'.format(batch_idx)))
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 


class IdentitySampler(Sampler):
&nbsp; &nbsp; """Sample person identities evenly in each batch.
&nbsp; &nbsp; &nbsp; &nbsp; Args:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; train_color_label, train_thermal_label: labels of two modalities
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; color_pos, thermal_pos: positions of each identity
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; batchSize: batch size
&nbsp; &nbsp; """

&nbsp; &nbsp; def __init__(self, train_color_label, train_thermal_label, color_pos, thermal_pos, num_pos, batchSize, epoch): &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; uni_label = np.unique(train_color_label)
&nbsp; &nbsp; &nbsp; &nbsp; self.n_classes = len(uni_label)
&nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; N = np.maximum(len(train_color_label), len(train_thermal_label)) 
&nbsp; &nbsp; &nbsp; &nbsp; for j in range(int(N/(batchSize*num_pos))+1):
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; batch_idx = np.random.choice(uni_label, batchSize, replace = False) &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; for i in range(batchSize):
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; sample_color &nbsp;= np.random.choice(color_pos[batch_idx[i]], num_pos)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; sample_thermal = np.random.choice(thermal_pos[batch_idx[i]], num_pos)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if j ==0 and i==0:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; index1= sample_color
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; index2= sample_thermal
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; else:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; index1 = np.hstack((index1, sample_color))
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; index2 = np.hstack((index2, sample_thermal))
&nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; self.index1 = index1
&nbsp; &nbsp; &nbsp; &nbsp; self.index2 = index2
&nbsp; &nbsp; &nbsp; &nbsp; self.N &nbsp;= N
&nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; def __iter__(self):
&nbsp; &nbsp; &nbsp; &nbsp; return iter(np.arange(len(self.index1)))

&nbsp; &nbsp; def __len__(self):
&nbsp; &nbsp; &nbsp; &nbsp; return self.N &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;


# training
print('==&gt; Start Training...')
print('==&gt; Preparing Data Loader...')
# identity sampler
epoch=0
print(trainset.train_color_label)
sampler = IdentitySampler(trainset.train_color_label, trainset.train_thermal_label, color_pos, thermal_pos, args.num_pos, args.batch_size, epoch)

trainset.cIndex = sampler.index1 &nbsp;# color index
trainset.tIndex = sampler.index2 &nbsp;# thermal index
print(epoch)
print(trainset.cIndex)
print(trainset.tIndex)

loader_batch = args.batch_size * args.num_pos

trainloader = data.DataLoader(trainset, batch_size=loader_batch, \
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; sampler=sampler, num_workers=args.workers, drop_last=True)
# training
train(epoch)











***@***.***:~/autodl-tmp/LLCM-main/AGW# python tsne.py  ========== Args:Namespace(arch='resnet50', batch_size=20, dataset='sysu', dist_type='l2', gpu='0', img_h=288, img_w=144, log_path='log/', lr=0.03, margin=0.3, margin_cc=0.1, method='base', mode='all', model_path='save_model/', num_pos=30, optim='sgd', resume='sysu_agw_p4_n8_lr_0.1_seed_0_best.t', save_epoch=20, seed=0, test_batch=64, test_only=False, trial=1, vis_log_path='log/vis_log/', workers=8) ========== ==&gt; Loading data.. [ToPILImage(), RandomCrop(size=(288, 144), padding=None), RandomHorizontalFlip(p=0.5), ToTensor(), Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])] Dataset sysu statistics:   ------------------------------   subset   | # ids | # images   ------------------------------   visible  |   395 |    22258   thermal  |   395 |    11909   ------------------------------ Data Loading Time:       4.081 ==&gt; Building model.. ==&gt; loading checkpoint sysu_agw_p4_n8_lr_0.1_seed_0_best.t ==&gt; loaded checkpoint sysu_agw_p4_n8_lr_0.1_seed_0_best.t (epoch 44) ==&gt; Start Training... ==&gt; Preparing Data Loader... [  0   0   0 ... 394 394 394] 0 [20927 20945 20945 ...  2936  2895  2884] [10606 10605 10598 ...  1191  1189  1188] 0 Traceback (most recent call last):   File "tsne.py", line 383, in <module&gt;     train(epoch)   File "tsne.py", line 320, in train     X_tsne = tsne.fit_transform(out.detach().cpu().numpy())   File "/root/miniconda3/lib/python3.8/site-packages/sklearn/manifold/_t_sne.py", line 932, in fit_transform     embedding = self._fit(X)   File "/root/miniconda3/lib/python3.8/site-packages/sklearn/manifold/_t_sne.py", line 702, in _fit     X = self._validate_data(X, accept_sparse=['csr'],   File "/root/miniconda3/lib/python3.8/site-packages/sklearn/base.py", line 421, in _validate_data     X = check_array(X, **check_params)   File "/root/miniconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f     return f(*args, **kwargs)   File "/root/miniconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 659, in check_array     raise ValueError("Found array with dim %d. %s expected <= 2." ValueError: Found array with dim 4. Estimator expected <= 2.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月9日(星期五) 中午1:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZYK100/LLCM] llcm数据集 (Issue #28)














  
您好，我在可视化过程中遇到问题ValueError: Found array with dim 4. TSNE expected <= 2.应该如何解决呢
  
您好，您可以将您修改后的代码发上来吗？我们原始的代码是没有这个问题的，不清楚您做了哪些修改

**Comment by quzongbo** [comment]
作者您好，我申请了您的LLCM数据集使用，希望您查看一下

**Comment by KongWeiKai** [comment]
作者您好，我申请了您的LLCM数据集使用，希望您查看一下
