### ISSUE TITLE
在SYSU和RegDB数据集上最好的epoch分别是多少呢？

### ISSUE THREAD

**Issue by YiXinXing** [ZYK100/LLCM#7]
您好！请问一下在使用这份代码，训练SYSU和RegDB数据集时，最好的epoch分别是多少呢？谢谢！！！

**Comment by ZYK100** [comment]
您好，因为代码会有一定的性能波动，所以最好的epoch不一定，大概都是在80以后

**Comment by YiXinXing** [comment]
好的！！谢谢您！！！
